<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller; use App\Models\StockApiSyncRecord; use App\Models\Warehouse; use Carbon\CarbonImmutable; use Illuminate\Database\Query\Builder; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class StockController extends Controller {
 public function index(Request $r): JsonResponse { [$f,$err]=$this->filters($r);if($err)return $err;$now=now('Asia/Jakarta');$q=$f['as_of']?$this->historical($f['as_of'],$f['warehouse_id']):StockApiSyncRecord::query();if(!$f['as_of']){$f['updated_since']&&$q->where('source_updated_at','>=',$f['updated_since']);$q->where('source_updated_at','<=',$f['updated_until']??$now);} $total=(clone$q)->count();$rows=$f['as_of']?$q->orderBy('sr.sku')->forPage($f['page'],$f['per_page'])->get():$q->orderBy('source_updated_at')->orderBy('sku')->forPage($f['page'],$f['per_page'])->get();return response()->json(['success'=>true,'meta'=>['warehouse_code'=>config('stock_api.warehouse_code'),'server_time'=>$now->toIso8601String(),'page'=>$f['page'],'per_page'=>$f['per_page'],'total'=>$total,'total_pages'=>(int)ceil($total/$f['per_page'])],'data'=>$rows->map(fn(object $x)=>['sku'=>$x->sku,'name'=>$x->name,'category'=>$x->category,'uom'=>$x->uom,'qty'=>(float)($x->historical_qty??$x->qty),'min_qty'=>$x->min_qty===null?null:(float)$x->min_qty,'status'=>$x->status,'updated_at'=>$this->iso($x->historical_updated_at??$x->source_updated_at)])->values()]); }
 private function historical(CarbonImmutable $date,int $wid):Builder{$ledger=DB::table('stock_mutations')->select('item_id')->selectRaw("SUM(CASE WHEN direction='in' THEN qty ELSE -qty END) as qty_as_of")->selectRaw('MAX(occurred_at) as last_mutation_at')->where('warehouse_id',$wid)->where('is_void',false)->where('occurred_at','<=',$date)->groupBy('item_id');return DB::table('stock_api_sync_records as sr')->leftJoinSub($ledger,'ledger','ledger.item_id','=','sr.item_id')->select(['sr.sku','sr.name','sr.category','sr.uom','sr.min_qty','sr.status','sr.source_updated_at',DB::raw("CASE WHEN sr.status='deleted' THEN 0 ELSE GREATEST(0,COALESCE(ledger.qty_as_of,0)) END as historical_qty"),DB::raw('COALESCE(ledger.last_mutation_at,sr.source_updated_at) as historical_updated_at')]);}
 private function filters(Request $r):array{$p=filter_var($r->input('page',1),FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$pp=filter_var($r->input('per_page',100),FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>500]]);if($p===false||$pp===false)return[[],$this->bad('page dan per_page harus berupa integer positif; per_page maksimum 500.')];$s=$this->time($r->input('updated_since'));$u=$this->time($r->input('updated_until'));if($s===false||$u===false)return[[],$this->bad('updated_since dan updated_until harus ISO-8601 dengan offset zona waktu.')];if($s&&$u&&$s->gt($u))return[[],$this->bad('updated_since tidak boleh melebihi updated_until.')];$a=$this->date($r->input('as_of'));if($a===false)return[[],$this->bad('as_of harus berupa tanggal YYYY-MM-DD yang valid (WIB).')];if($a&&($s||$u))return[[],$this->bad('as_of tidak dapat dipakai bersama updated_since atau updated_until.')];$wid=(int)Warehouse::where('code',config('stock_api.source_warehouse_code'))->value('id');if($wid<=0)return[[],$this->config('Gudang sumber API tidak ditemukan.')];return[['page'=>$p,'per_page'=>$pp,'updated_since'=>$s,'updated_until'=>$u,'as_of'=>$a,'warehouse_id'=>$wid],null];}
 private function time(mixed $v):CarbonImmutable|false|null{if($v===null||$v==='')return null;if(!is_string($v)||!preg_match('/T.*(?:Z|[+-]\\d{2}:\\d{2})$/',$v))return false;try{return CarbonImmutable::parse($v);}catch(\Throwable){return false;}}
 private function date(mixed $v):CarbonImmutable|false|null{if($v===null||$v==='')return null;if(!is_string($v)||!preg_match('/^\\d{4}-\\d{2}-\\d{2}$/',$v))return false;try{$d=CarbonImmutable::createFromFormat('!Y-m-d',$v,'Asia/Jakarta');return$d->format('Y-m-d')===$v?$d->endOfDay():false;}catch(\Throwable){return false;}}
 private function iso(mixed $v):string{return($v instanceof\DateTimeInterface?CarbonImmutable::instance($v):CarbonImmutable::parse($v))->setTimezone('Asia/Jakarta')->toIso8601String();}private function bad(string$m):JsonResponse{return response()->json(['success'=>false,'error'=>['code'=>'INVALID_PARAMETER','message'=>$m]],400);}private function config(string$m):JsonResponse{return response()->json(['success'=>false,'error'=>['code'=>'API_CONFIGURATION_ERROR','message'=>$m]],503);}
}
